Updates to the latest babel configurations (babel-preset-env)
ship-components/react-outsideclick pull request #2
Opened 2017-04-21 22:50 UTC by ThinkTankShark

2017-07-18 17:56 UTC, isuttell requested changes

2017-07-18 17:56 UTC, isuttell commented on package.json
> +  "dependencies": {
Is this a dependency or a devDependency?

2017-07-26 20:30 UTC, ThinkTankShark commented on package.json
> +  "dependencies": {
Good catch, moved it to devDep

2017-07-26 20:41 UTC, isuttell approved these changes

2017-07-26 20:41 UTC, isuttell commented on .eslintrc
> -    "react/jsx-quotes": 1,
We should switch to the ship components eslint config

2017-07-26 20:48 UTC, merged

2017-07-26 20:49 UTC, ThinkTankShark commented on .eslintrc
> -    "react/jsx-quotes": 1,
Sure, will do next time I push